# Generated by Django 4.2.7 on 2023-12-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40)),
                ('passed_theme', models.BooleanField(default=0)),
                ('summary', models.TextField(null=True)),
                ('reference_data', models.ManyToManyField(to='learning.educationalresource')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('theme_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.themelist')),
            ],
        ),
    ]
