# Generated by Django 4.2.7 on 2023-12-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='theme_data',
        ),
        migrations.AddField(
            model_name='object',
            name='theme_data',
            field=models.ManyToManyField(to='learning.themelist'),
        ),
    ]
