# Generated by Django 4.2.7 on 2023-12-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_object_theme_data_object_theme_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themelist',
            name='summary',
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
