# Generated by Django 4.2.7 on 2023-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_themelist_summary_educationalresource_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40)),
                ('passed_theme', models.BooleanField(default=0)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='summary',
        ),
        migrations.DeleteModel(
            name='ThemeList',
        ),
        migrations.AddField(
            model_name='theme',
            name='educational_data',
            field=models.ManyToManyField(to='learning.educationalresource'),
        ),
        migrations.AlterField(
            model_name='object',
            name='theme_data',
            field=models.ManyToManyField(to='learning.theme'),
        ),
    ]
