# Generated by Django 4.2.7 on 2023-12-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_theme_remove_educationalresource_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='theme',
            new_name='name',
        ),
    ]
