# Generated by Django 4.2.7 on 2023-12-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_theme_theme_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='theme',
        ),
    ]
