# Generated by Django 4.2.7 on 2023-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_rename_name_theme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='passed_theme',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
