# Generated by Django 4.2.7 on 2023-12-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_theme_passed_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
