# Generated by Django 4.2.7 on 2023-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_theme_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
