# Generated by Django 4.2.7 on 2023-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_object_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
