# Generated by Django 4.2.7 on 2023-12-24 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0010_object_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
