# Generated by Django 4.2.7 on 2023-12-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_object_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='name',
            new_name='object',
        ),
        migrations.RemoveField(
            model_name='object',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='object',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='object',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='passed_theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='summary',
        ),
    ]
