# Generated by Django 4.2.7 on 2023-12-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0012_rename_name_object_object_remove_object_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('passed_theme', models.BooleanField(default=False, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserObjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
