# Generated by Django 4.2.7 on 2023-12-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_userthemedata_userobjectdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthemedata',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.object'),
        ),
    ]
