# Generated by Django 4.2.7 on 2023-12-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_testslist_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testslist',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testslist',
            name='user',
        ),
        migrations.DeleteModel(
            name='WrongAnswer',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestsList',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
