# Generated by Django 4.2.7 on 2023-12-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0002_answer_delete_wronganswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='wrong_answer',
            new_name='answer',
        ),
    ]
