# Generated by Django 4.2.7 on 2023-12-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testslist',
            name='test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.test'),
        ),
    ]
